services:
  configserver:
    image: "aytugakin/config-server/v1:latest"
    container_name: config-server
    ports:
      - "9296:9296"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ordanoraya
  bus:
    image: "aytugakin/bus-service/v1:latest"
    container_name: bus-service
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ordanoraya
    environment:
      SPRING_APPLICATION_NAME: bus-service
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:9296"
      SPRING_PROFILES_ACTIVE: default
  car:
    image: "aytugakin/car-service/v1:latest"
    container_name: car-service
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ordanoraya
    environment:
      SPRING_APPLICATION_NAME: car-service
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:9296"
      SPRING_PROFILES_ACTIVE: default
  travel:
    image: "aytugakin/travel-service/v1:latest"
    container_name: travel-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ordanoraya
    environment:
      SPRING_APPLICATION_NAME: travel-service
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:9296"
      SPRING_PROFILES_ACTIVE: default
networks:
  ordanoraya:
    driver: "bridge"