spring:
  application:
    name: car-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aytug
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"