server:
  port: 9090
spring:
  application:
    name: api-gw
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: BUS-SERVICE
          uri: lb://bus-service
          predicates:
            - Path=/api/bus/**
        - id: CAR-SERVICE
          uri: lb://car-service
          predicates:
            - Path=/api/car/**
        - id: travel_route
          uri: lb://travel-service
          predicates:
            - Path=/api/travel/**
logging:
  level:
    com:
      aytugakin:
        gw: DEBUG