server:
  port: 9090
spring:
  application:
    name: api-gw
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : bus-service
          uri: lb://bus-service
          predicates:
            - Path=/api/bus/**
          filters:
            - name: CircuitBreaker
              args:
                name: bus-service
                fallbackUri: forward:/fallback/busServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/car/**
          filters:
            - name: CircuitBreaker
              args:
                name: car-service
                fallbackUri: forward:/fallback/carServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: TRAVEL-SERVICE
          uri: lb://TRAVEL-SERVICE
          predicates:
            - Path=/api/travel/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRAVEL-SERVICE
                fallbackUri: forward:/fallback/travelServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1