server:
  port: 9090
spring:
  application:
    name: api-gw
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : BUS-SERVICE
          uri: lb://BUS-SERVICE
          predicates:
            - Path=/api/bus/**
          filters:
            - name: CircuitBreaker
              args:
                name: BUS-SERVICE
                fallbackuri: forward:/busServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: CAR-SERVICE
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/api/car/**
          filters:
            - name: CircuitBreaker
              args:
                name: CAR-SERVICE
                fallbackuri: forward:/carServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: TRAVEL-SERVICE
          uri: lb://TRAVEL-SERVICE
          predicates:
            - Path=/api/travel/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRAVEL-SERVICE
                fallbackuri: forward:/travelServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1