server:
  port: 9090
spring:
  application:
    name: api-gw
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: BUS-SERVICE
          uri: lb://bus-service
          predicates:
            - Path=/api/bus/**
        - id: CAR-SERVICE
          uri: lb://car-service
          predicates:
            - Path=/api/car/**
        - id: TRAVEL-SERVICE
          uri: lb://travel-service
          predicates:
            - Path=/api/travel/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
logging:
  level:
    com:
      aytugakin:
        gw: DEBUG