server:
  port: 9090
spring:
  application:
    name: api-gw
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true